# Generated by Django 3.2.4 on 2021-06-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultroom',
            new_name='roomno',
        ),
    ]
